<a href="https://colab.research.google.com/github/sugandhasrivastava0610-blip/credit_card_fraud_detection/blob/main/Credit_card_fraud.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
credit_card_data = pd.read_csv('https://www.kaggle.com/datasets/arockiaselciaa/creditcardcsv')

ParserError: Error tokenizing data. C error: Expected 1 fields in line 9, saw 2

In [ ]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11959 entries, 0 to 11958
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    11959 non-null  int64
 1   V1      11959 non-null  float64
 2   V2      11959 non-null  float64
 3   V3      11959 non-null  float64
 4   V4      11959 non-null  float64
 5   V5      11959 non-null  float64
 6   V6      11959 non-null  float64
 7   V7      11959 non-null  float64
 8   V8      11959 non-null  float64
 9   V9      11959 non-null  float64
 10  V10     11959 non-null  float64
 11  V11     11959 non-null  float64
 12  V12     11959 non-null  float64
 13  V13     11959 non-null  float64
 14  V14     11959 non-null  float64
 15  V15     11959 non-null  float64
 16  V16     11959 non-null  float64
 17  V17     11959 non-null  float64
 18  V18     11959 non-null  float64
 19  V19     11959 non-null  float64
 20  V20     11958 non-null  float64
 21  V21     11958 non-null  float64
 22  V22     11958 non-null  float64
 23  V23     11958 non-null  float64
 24  V24     11958 non-null  float64
 25  V25     11958 non-null  float64
 26  V26     11958 non-null  float64
 27  V27     11958 non-null  float64
 28  V28     11958 non-null  float64
 29  Amount  11958 non-null  float64
 30  Class   11958 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 2.8 MB

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
11954,20631,1.504204,-0.411728,0.200090,-0.778753,-0.442232,-0.119677,-0.782660,-0.165178,0.691819,...,-0.136231,-0.217274,-0.143260,-1.057332,0.529188,-0.235062,-0.012089,0.000905,9.00,0.0
11955,20636,1.134994,0.096340,0.277921,0.319692,0.742800,1.611803,-0.458649,0.390012,1.424541,...,-0.395605,-0.743542,0.222256,-1.859104,-0.109777,0.279049,0.012398,-0.009090,0.99,0.0
11956,20638,-6.305012,3.944886,-4.707362,1.539602,-3.934785,-1.730565,-2.104936,3.843447,0.863458,...,0.073140,-0.039935,-0.108896,0.691434,-0.261979,-0.447540,0.212900,-0.031021,89.99,0.0
11957,20638,1.161960,-0.398297,1.123732,-0.474237,-1.226667,-0.519325,-0.804179,0.070134,3.262926,...,-0.121191,0.097255,0.050903,0.330479,0.315692,-0.712765,0.073836,0.028055,11.85,0.0
11958,20642,1.291096,-0.226628,0.708386,-0.719236,-0.659099,-0.273757,-0.612042,-0.111488,3.032258,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11959 entries, 0 to 11958
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    11959 non-null  int64
 1   V1      11959 non-null  float64
 2   V2      11959 non-null  float64
 3   V3      11959 non-null  float64
 4   V4      11959 non-null  float64
 5   V5      11959 non-null  float64
 6   V6      11959 non-null  float64
 7   V7      11959 non-null  float64
 8   V8      11959 non-null  float64
 9   V9      11959 non-null  float64
 10  V10     11959 non-null  float64
 11  V11     11959 non-null  float64
 12  V12     11959 non-null  float64
 13  V13     11959 non-null  float64
 14  V14     11959 non-null  float64
 15  V15     11959 non-null  float64
 16  V16     11959 non-null  float64
 17  V17     11959 non-null  float64
 18  V18     11959 non-null  float64
 19  V19     11959 non-null  float64
 20  V20     11958 non-null  float64
 21  V21     11958 non-null  float64
 22  V22     11958 non-null  float64
 23  V23     11958 non-null  float64
 24  V24     11958 non-null  float64
 25  V25     11958 non-null  float64
 26  V26     11958 non-null  float64
 27  V27     11958 non-null  float64
 28  V28     11958 non-null  float64
 29  Amount  11958 non-null  float64
 30  Class   11958 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 2.8 MB

In [ ]:
credit_card_data.sum()

Time      9.579155e+07
V1       -2.585889e+03
V2        3.313807e+03
V3        1.063759e+04
V4        3.379679e+03
V5       -1.035472e+03
V6        1.674093e+03
V7       -1.458315e+03
V8       -5.827272e+02
V9        1.090157e+04
V10      -3.418657e+03
V11       9.809559e+03
V12      -1.725255e+04
V13       1.117786e+04
V14       9.352791e+03
V15      -2.142813e+03
V16      -2.985964e+02
V17       4.539042e+03
V18      -2.681141e+02
V19      -7.878225e+02
V20       2.694565e+02
V21      -7.351067e+02
V22      -1.839743e+03
V23      -4.030977e+02
V24       2.046371e+02
V25       1.253129e+03
V26       7.520462e+02
V27       9.949138e+01
V28       3.245973e+00
Amount    7.456126e+05
Class     5.200000e+01
dtype: float64

In [ ]:
credit_card_data['Class'].value_counts()

Class
0.0    11906
1.0       52
Name: count, dtype: int64

This dataset is highly unbalanced

0 -> Normal Transaction

1 -> Fraudulent transaction

In [ ]:
legit= credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(11906, 31)
(52, 31)

In [ ]:
legit.Amount.describe()

count    11906.000000
mean        62.198127
std        177.379105
min          0.000000
25%          5.292500
50%         15.950000
75%         50.000000
max       7712.430000
Name: Amount, dtype: float64

In [ ]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,7993.389048,-0.200839,0.259753,0.929229,0.255987,-0.076685,0.149326,-0.097364,-0.053087,0.927305,...,0.020836,-0.063076,-0.154427,-0.032369,0.018962,0.105861,0.061825,0.005330,0.000012,62.198127
1.0,11569.615385,-3.769104,4.258027,-8.202329,6.396396,-2.342431,-1.990562,-5.740207,0.950650,-2.729769,...,0.411236,0.305259,-0.021762,-0.340563,-0.406311,-0.139505,0.306967,0.692927,0.059751,97.724808

Under Sampling

In [ ]:
legit_sample = legit.sample(n=492)

Concatinating two Dataframes

In [ ]:
new_dataset= pd.concat([legit_sample, fraud],axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
8740,11881,1.328610,-0.070211,0.323257,0.198739,-0.299839,-0.243293,-0.316549,-0.155565,2.134861,...,-0.323354,-0.427929,-0.147831,-0.417558,0.530536,1.125932,-0.094634,-0.015683,3.30,0.0
4968,4528,0.633463,-1.392735,0.792475,-0.792777,-1.552783,-0.495482,-0.436007,-0.078556,3.183035,...,0.056501,0.001172,-0.192657,0.412068,0.108028,-0.087514,-0.021529,0.070741,300.00,0.0
9362,13664,0.051862,0.780484,1.086097,0.515425,0.336862,-0.276226,0.428111,-0.171277,0.894032,...,-0.351117,-0.798547,0.192334,-0.521133,-0.864037,-0.003489,0.065201,0.095705,30.58,0.0
2474,2039,-0.716538,1.303612,0.407028,0.493151,-0.708351,0.023400,0.875334,-0.624368,-0.700866,...,0.647784,-0.651065,0.293746,-0.150012,-0.248821,-0.700840,0.066817,-0.047763,178.84,0.0
107,71,1.331897,-0.579962,0.422606,-0.897752,-0.746254,-0.056273,-0.750317,0.128484,-0.964682,...,-0.039070,-0.255174,0.109333,-0.328448,0.162254,-0.447276,0.020071,0.006231,14.48,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
10897,18690,-15.398845,7.472324,-19.026912,11.165526,-6.893856,-2.120937,-14.913330,-0.721214,-7.175097,...,-2.444884,0.727495,-0.345078,-0.981749,0.995271,0.816762,2.262942,-1.178063,1.0,1.0
11343,19762,-14.179165,7.421370,-21.405836,11.927512,-7.974281,-2.202710,-15.471612,-0.356595,-6.380125,...,-2.366836,1.130955,0.991153,-1.033132,-0.327179,0.634693,2.171905,-1.395288,1.0,1.0
11710,20011,-14.724627,7.875157,-21.872317,11.906170,-8.348734,-2.262846,-15.833443,0.077874,-6.356833,...,-2.362345,1.099557,1.037199,-1.036359,-0.254777,0.642343,2.161129,-1.401282,1.0,1.0
11841,20332,-15.271362,8.326581,-22.338591,11.885313,-8.721334,-2.324307,-16.196419,0.512882,-6.333685,...,-2.356896,1.068019,1.085617,-1.039797,-0.182006,0.649921,2.149247,-1.406811,1.0,1.0
11880,20451,-15.819179,8.775997,-22.804686,11.864868,-9.092361,-2.386893,-16.560368,0.948349,-6.310658,...,-2.350634,1.036362,1.136051,-1.043414,-0.108923,0.657437,2.136424,-1.411945,1.0,1.0

In [ ]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0     52
Name: count, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,8024.182927,-0.301363,0.264332,0.826984,0.274881,-0.078516,0.105186,-0.100297,-0.099539,1.007072,...,-0.029206,-0.080406,-0.157828,-0.048542,0.010549,0.112031,0.075777,-0.006248,-0.023163,66.094065
1.0,11569.615385,-3.769104,4.258027,-8.202329,6.396396,-2.342431,-1.990562,-5.740207,0.950650,-2.729769,...,0.411236,0.305259,-0.021762,-0.340563,-0.406311,-0.139505,0.306967,0.692927,0.059751,97.724808

Splitting data into features & targets

In [ ]:
x= new_dataset.drop(columns='Class', axis=1)
y= new_dataset['Class']

In [ ]:
print(x)

        Time         V1        V2         V3         V4        V5        V6  \
8740   11881   1.328610 -0.070211   0.323257   0.198739 -0.299839 -0.243293
4968    4528   0.633463 -1.392735   0.792475  -0.792777 -1.552783 -0.495482
9362   13664   0.051862  0.780484   1.086097   0.515425  0.336862 -0.276226
2474    2039  -0.716538  1.303612   0.407028   0.493151 -0.708351  0.023400
107       71   1.331897 -0.579962   0.422606  -0.897752 -0.746254 -0.056273
...      ...        ...       ...        ...        ...       ...       ...
10897  18690 -15.398845  7.472324 -19.026912  11.165526 -6.893856 -2.120937
11343  19762 -14.179165  7.421370 -21.405836  11.927512 -7.974281 -2.202710
11710  20011 -14.724627  7.875157 -21.872317  11.906170 -8.348734 -2.262846
11841  20332 -15.271362  8.326581 -22.338591  11.885313 -8.721334 -2.324307
11880  20451 -15.819179  8.775997 -22.804686  11.864868 -9.092361 -2.386893

              V7        V8        V9  ...       V20       V21       V22  \
8740   -0.316549 -0.155565  2.134861  ... -0.115175 -0.323354 -0.427929
4968   -0.436007 -0.078556  3.183035  ...  0.420357  0.056501  0.001172
9362    0.428111 -0.171277  0.894032  ...  0.106352 -0.351117 -0.798547
2474    0.875334 -0.624368 -0.700866  ... -0.262795  0.647784 -0.651065
107    -0.750317  0.128484 -0.964682  ...  0.052489 -0.039070 -0.255174
...          ...       ...       ...  ...       ...       ...       ...
10897 -14.913330 -0.721214 -7.175097  ...  1.111502 -2.444884  0.727495
11343 -15.471612 -0.356595 -6.380125  ...  1.002764 -2.366836  1.130955
11710 -15.833443  0.077874 -6.356833  ...  0.996469 -2.362345  1.099557
11841 -16.196419  0.512882 -6.333685  ...  0.993121 -2.356896  1.068019
11880 -16.560368  0.948349 -6.310658  ...  0.992279 -2.350634  1.036362

            V23       V24       V25       V26       V27       V28  Amount
8740  -0.147831 -0.417558  0.530536  1.125932 -0.094634 -0.015683    3.30
4968  -0.192657  0.412068  0.108028 -0.087514 -0.021529  0.070741  300.00
9362   0.192334 -0.521133 -0.864037 -0.003489  0.065201  0.095705   30.58
2474   0.293746 -0.150012 -0.248821 -0.700840  0.066817 -0.047763  178.84
107    0.109333 -0.328448  0.162254 -0.447276  0.020071  0.006231   14.48
...         ...       ...       ...       ...       ...       ...     ...
10897 -0.345078 -0.981749  0.995271  0.816762  2.262942 -1.178063    1.00
11343  0.991153 -1.033132 -0.327179  0.634693  2.171905 -1.395288    1.00
11710  1.037199 -1.036359 -0.254777  0.642343  2.161129 -1.401282    1.00
11841  1.085617 -1.039797 -0.182006  0.649921  2.149247 -1.406811    1.00
11880  1.136051 -1.043414 -0.108923  0.657437  2.136424 -1.411945    1.00

[544 rows x 30 columns]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

In [ ]:
print(x.shape,x_train.shape,x_test.shape)

(544, 30) (435, 30) (109, 30)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

Model Training- Logistic Regression

In [ ]:
model_scaled = LogisticRegression()
model_scaled.fit(x_train_scaled, y_train)

LogisticRegression()

Model Evaluation

In [ ]:
X_train_prediction = model_scaled.predict(x_train_scaled)

In [ ]:
train_data_accuracy = accuracy_score(X_train_prediction, y_train)

In [ ]:
print('Accuracy on training data:',train_data_accuracy)

Accuracy on training data: 0.9908045977011494

In [ ]:
x_test_prediction = model_scaled.predict(x_test_scaled)

In [ ]:
test_data_accuracy = accuracy_score(x_test_prediction, y_test)

In [ ]:
print("Accuracy score on test data:", test_data_accuracy)

Accuracy score on test data: 0.9908256880733946

In [ ]:
import joblib

joblib.dump(model_scaled, "fraud_model.pkl")

print("Model saved successfully")

Model saved successfully

In [ ]:
import gradio as gr
import pandas as pd
import joblib

model = joblib.load("fraud_model.pkl")

def predict_fraud(*features):

    columns = [
        "V1","V2","V3","V4","V5","V6","V7","V8",
        "V9","V10","V11","V12","V13","V14","V15","V16",
        "V17","V18","V19","V20","V21","V22","V23","V24",
        "V25","V26","V27","V28","Amount"
    ]

    data = pd.DataFrame([features], columns=columns)

    prediction = model.predict(data)[0]

    if hasattr(model, "predict_proba"):
        confidence = max(model.predict_proba(data)[0])
    else:
        confidence = "N/A"

    result = (
        "🚨 Fraudulent Transaction"
        if prediction == 1
        else "✅ Legitimate Transaction"
    )

    return result, confidence


inputs = [
    gr.Number(label=f"V{i}")
    for i in range(1, 29)
]

inputs.append(
    gr.Number(label="Amount")
)

demo = gr.Interface(
    fn=predict_fraud,
    inputs=inputs,
    outputs=[
        gr.Textbox(label="Prediction"),
        gr.Textbox(label="Confidence")
    ],
    title="Credit Card Fraud Detection",
    description="Predict whether a transaction is fraudulent or legitimate."
)

demo.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://dcec03c072f79f0b94.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)